import type { MetadataRoute } from 'next';

/**
 * robots.txt generated by Next.js. Routed at /robots.txt.
 * Allows everything on the marketing root, blocks API routes and the
 * /landing duplicate URL. The app subdomain serves its own implicit
 * robots (everything indexable by default — but it's only auth-gated app
 * pages so it doesn't matter much).
 */
export default function robots(): MetadataRoute.Robots {
    return {
        rules: [
            {
                userAgent: '*',
                allow: '/',
                disallow: [
                    '/api/',
                    '/landing',  // canonical is /
                ],
            },
        ],
        sitemap: 'https://yourfriendleague.com/sitemap.xml',
        host: 'https://yourfriendleague.com',
    };
}
